const mongoose=require('mongoose');
const schema = mongoose.Schema;
const addAssetSchema=mongoose.Schema({
    discardCheck:{type:Boolean,default:false},
    assetName:{type:String},
    assetImage:{type:String},
    assetimageOriginal:{type:String},
    uploadFilespath:{type:String},
    uploadfilesorginal:{type:String},
    assetCode:{type:String},
    category:{ type:schema.ObjectId,ref:"Category"},
    location:{ type:schema.ObjectId,ref:"Location"},
    status:{ type:schema.ObjectId,ref:"Status"},
    condition:{ type:schema.ObjectId,ref:"Condition"},
    brand:{type:schema.ObjectId,ref:"Brand"},
    model:{type:schema.ObjectId,ref:"Model"},
    linkedAsset:[{type:mongoose.Schema.ObjectId,ref:"Asset"}],
    Description:{type:String},
    serialNo:{type:String},
    vendorName:{ type:schema.ObjectId,ref:"Vendor"},
    poNumber:{type:Number},
    invoiceDate:{type:Date},
    invoiceNo:{type:String},
    purchaseDate:{type:Date},
    purchasePrice:{type:Number},
    selfOwener:{type:Boolean},
    capitalizationPrice:{type:Number},
    endlifeDate:{type:Date},
    capitalizationDate:{type:Date},
    depreciationPercent:{type:Number},
    incomeTax:{type:Number},
    scrapValue:{type:String},
    accumulatedDepression:{type:Number},
    department:{ type:schema.ObjectId,ref:"Department"},
    transferredTo:{type:String},
    allottedUpto:{type:Date},
    remarks:{type:String},
    amcVendor:{ type:schema.ObjectId,ref:"Vendor"},
    warrantyVendor:{ type:schema.ObjectId,ref:"Vendor"},
    insurancestartdate:{type:Date},
    insuranceenddate:{type:Date},
    amcstartDate:{type:Date},
    amcendDate:{type:Date},
    warantystartDate:{type:Date},
    warantyendDate:{type:Date},
})
module.exports=mongoose.model('Asset',addAssetSchema);